In [40]:
sims_apo = "C:/Users/fbellina/Desktop/file_gromacs/CV_script/State_1/"
sims_holo = "C:/Users/fbellina/Desktop/file_gromacs/CV_script/State_2/"

In [2]:
print(PATH)

NameError: name 'PATH' is not defined

In [41]:
#emoved in version 2.1, so it is no longer available. Here's an updated version of the previous script that uses the MDAnalysis.lib.distances module instead:

import numpy as np
import MDAnalysis as mda
from MDAnalysis.lib.distances import distance_array
import numpy as np
from MDAnalysis.analysis import distances

In [42]:
u = mda.Universe(f'{sims_holo}/md.tpr', f'{sims_holo}/state2.xtc')
atom_pairs = [(243,751), (243,784), (243,787),(243,794),(243,800),(246,751),(246,784),(246,787),(246,794),
(246,800)]
atoms = [u.select_atoms(f'bynum {serial_number}') for pair in atom_pairs for serial_number in pair]

dist_list = [[] for _ in range(len(atom_pairs))]
for ts in u.trajectory:
    for i, (atom1, atom2) in enumerate(zip(atoms[::2], atoms[1::2])):
        distance = distances.distance_array(atom1.positions, atom2.positions)
        dist_list[i].append(distance[0][0])

In [43]:
dist_list2=np.empty([len(dist_list),len(dist_list[0])])
#print(len(atom_pairs))
for i in np.arange(0,len(atom_pairs)):  #np.arange goes from the element on the right of the brackets up to the member on the left -1
    lmax=np.max(dist_list[i])
    dist_list2[i]=dist_list[i]/lmax
print(dist_list2[0])

[0.80896302 0.81151059 0.79624116 ... 0.92578078 0.90362767 0.89742705]


In [44]:
print("max distance in nm, useful for plumed:")
for i in range(0,9):
    print(np.max(dist_list[i])/10)

max distance in nm, useful for plumed:
2.110188031797431
2.2475077015508402
2.1731637906289847
2.5330902970815865
2.77578642912966
2.0688243587570443
2.2239089081517336
2.129631484286744
2.487219647977599


In [45]:
#import MDAnalysis as mda
#from MDAnalysis.analysis import distances
#import numpy as np

# Load the universe and select the atoms by their serial number
#u = mda.Universe(f'{sims_holo}/md.tpr', f'{sims_holo}/state2.xtc')
#atom_pairs = [(243,751), (243,784), (243,787),(243,794),(243,800),(246,751),(246,784),(246,787),(246,794),
#(246,800)] # Add all 12 pairs of atom serial numbers here
#atoms = [u.select_atoms(f'bynum {serial_number}') for pair in atom_pairs for serial_number in pair]

# Calculate the distance between each pair of atoms for each frame
#dist_list = [[] for _ in range(len(atom_pairs))]
#for ts in u.trajectory:
#    for i, (atom1, atom2) in enumerate(zip(atoms[::2], atoms[1::2])):
#        distance = distances.distance_array(atom1.positions, atom2.positions)
#        dist_list[i].append(distance[0][0])


# Calculate the mean distance and standard deviation for each pair of atoms
mean_distances = []
std_distances = []
for i, pair in enumerate(atom_pairs):
    mean_distance = np.mean(dist_list2[i])
    std_distance = np.std(dist_list2[i])
    mean_distances.append(mean_distance)
    std_distances.append(std_distance)
    
#save
# Combine the mean and standard deviation values for each pair of atoms into a single array
pair_values = np.zeros((len(mean_distances), 2))
pair_values[:, 0] = mean_distances
pair_values[:, 1] = std_distances

# Save the pair values to a binary file using NumPy's save function
np.save('Holo_values.npy', pair_values)


In [46]:
Holo_values = np.load('Holo_values.npy')
print(Holo_values)

[[0.83005155 0.05688485]
 [0.85119934 0.05156362]
 [0.83756913 0.05456168]
 [0.77919531 0.0745246 ]
 [0.79928608 0.06492137]
 [0.84472131 0.05277814]
 [0.85971354 0.05317734]
 [0.86363759 0.04996707]
 [0.81986752 0.06450067]
 [0.84242226 0.05539253]]


In [47]:
u = mda.Universe(f'{sims_apo}/md.tpr', f'{sims_apo}/state1.xtc')
atom_pairs = [(243,751), (243,784), (243,787),(243,794),(243,800),(246,751),(246,784),(246,787),(246,794),
(246,800)] # Add all 12 pairs of atom serial numbers here
atoms = [u.select_atoms(f'bynum {serial_number}') for pair in atom_pairs for serial_number in pair]

# Calculate the distance between each pair of atoms for each frame
dist_list = [[] for _ in range(len(atom_pairs))]
for ts in u.trajectory:
    for i, (atom1, atom2) in enumerate(zip(atoms[::2], atoms[1::2])):
        distance = distances.distance_array(atom1.positions, atom2.positions)
        dist_list[i].append(distance[0][0])
        
dist_list2=np.empty([len(dist_list),len(dist_list[0])])
#print(len(atom_pairs))
for i in np.arange(0,len(atom_pairs)):  #np.arange goes from the element on the right of the brackets up to the member on the left -1
    lmax=np.max(dist_list[i])
    dist_list2[i]=dist_list[i]/lmax
#print(dist_list2[0])

# Calculate the mean distance and standard deviation for each pair of atoms
mean_distances = []
std_distances = []
for i, pair in enumerate(atom_pairs):
    mean_distance = np.mean(dist_list2[i])
    std_distance = np.std(dist_list2[i])
    mean_distances.append(mean_distance)
    std_distances.append(std_distance)

# Combine the mean and standard deviation values for each pair of atoms into a single array
pair_values = np.zeros((len(mean_distances), 2))
pair_values[:, 0] = mean_distances
pair_values[:, 1] = std_distances

# Save the pair values to a binary file using NumPy's save function
np.save('Apo_values.npy', pair_values)

In [48]:
Apo_values = np.load('Apo_values.npy')
print(Apo_values)

[[0.56038019 0.05394175]
 [0.4604151  0.09868002]
 [0.51752965 0.08566271]
 [0.66776414 0.06049872]
 [0.6532369  0.0732032 ]
 [0.48639496 0.06997232]
 [0.41935725 0.13229133]
 [0.46444736 0.11444819]
 [0.61488262 0.07514033]
 [0.61627804 0.08682597]]


In [49]:
import numpy as np
import pandas as pd
# Define the data
Apo_values = np.load('Apo_values.npy')
Holo_values = np.load('Holo_values.npy')

# Calculate the HLDA scores
hlda_scores = ((Apo_values[:, 0] - Holo_values[:, 0])) * (1 / Apo_values[:, 1] + 1 / Holo_values[:, 1])

# Create a table with the results
results = pd.DataFrame(hlda_scores.reshape(1,-1), columns=['d'+str(i+1) for i in range(10)])

# Print the table
print(results)

        d1         d2        d3        d4        d5         d6         d7  \
0 -9.73996 -11.538796 -9.601687 -3.337103 -4.244752 -11.910267 -11.609587   

          d8        d9       d10  
0 -11.477022 -5.906055 -6.687145  
